About us, mission, how it works, features and benefits
Bashamega/ebookCraft pull request #13
Opened 2024-02-16 18:00 UTC by drewduong

2024-02-17 04:07 UTC, Bashamega commented on README.md
>  ## About
```suggestion

```

2024-02-17 04:07 UTC, Bashamega commented on README.md
> +About Us
```suggestion
## About Us
```

2024-02-17 04:08 UTC, Bashamega commented on README.md
> +Our Mission
```suggestion
## Our Mission
```

2024-02-17 04:08 UTC, Bashamega commented on README.md
> +How It Works
```suggestion
## How It Works
```

2024-02-17 04:09 UTC, Bashamega commented on README.md
> +Features and Benefits
```suggestion
## Features and Benefits
```

2024-02-17 04:09 UTC, Bashamega commented on README.md
> +Join Our Community
```suggestion
## Join Our Community
```

2024-02-17 04:09 UTC, Bashamega commented on README.md
> +eBook Craft leverages the power of HTML and CSS, the building blocks of the web, to give you unparalleled control over the layout and design of your eBooks. Whether you're looking to create a simple
```suggestion
E-Book Craft leverages the power of HTML and CSS, the building blocks of the web, to give you unparalleled control over the layout and design of your eBooks. Whether you're looking to create a simple text-based eBook or a complex interactive digital publication, our tool provides the flexibility you need. And the best part? You can add more tools and features to your eBook without any coding required.
```

2024-02-17 04:10 UTC, Bashamega requested changes
Thank you for contributing. I have requested some changes to make it better

2024-02-22 20:45 UTC, drewduong reviewed
You're welcome! Thanks for the changes.

2024-02-23 03:40 UTC, merged